spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jean
    username: root
    password: 1234

  sql:
    init:
     mode: always
     separator: $$

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false

    defer-datasource-initialization: true

  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB

  jwt:
    secret:
      66988d4bfcd57acb1f5af68428fcbc1b5e8ab5a6d549cdb1112b5ae359049cd0b2b360f36b7355a4b76283da89edb4bc5cb19b02ea8e7eeacffd9d4d1973643e
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1

  mail:
    host: smtp.gmail.com
    port: 587
    username: sunwoo1137@gmail.com
    password: vxgarwsiyvrzlpyp
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true